#!/bin/bash
# skript algab
#
# kasutajad vasatava parooliga
if [ $# -ne 1 ]; then
    echo "Kasutusjuhend: $0 failinimi"
else
failinimi=$1
  if [ -f $failinimi -a -r $failinimi ]; then
    echo "fail on olemas!"
    for nimi in $(cat $failinimi)
    do
        kasutajanimi=$(echo "$rida" | cut -f1 -d:)
        sh lisakasutaja $kasutajanimi
        echo "$rida" | chpasswd 123
    done
  else
    echo "Probleem failiga $failinimi"
  fi

